[package]
name = "tlib"
version = "0.4.0"
authors = ["T0mstone <realt0mstone@gmail.com>"]
edition = "2018"

[dependencies]
either = { version = "1.5.2", optional = true }

[features]
default = ["either"]

no_std = []
either_use_std = ["either/use_std"]
