[package]
name = "tlib"
version = "0.9.1"
authors = ["T0mstone <realt0mstone@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = {version = "0.2.11", optional = true}

[features]
default = []

use_std = []
pow = ["num-traits"]